language: go

go:
 - 1.4

before_install:
  - go get -d github.com/libgit2/git2go
  - cd $GOPATH/src/github.com/libgit2/git2go
  - git submodule update --init
  - make install

script:
  - go get golang.org/x/tools/cmd/vet
  - go build
  - go vet

notifications:
  email:
    - marty.schoch@gmail.com
